# -*- coding: utf-8 -*-
"""Python library

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TCMleVJgsN1LZH2wJz1chOG3kntsqqKa
"""

print("hello")

import pandas
from pandas import DataFrame
import matplotlib.pyplot as plt

data = pandas.read_csv('/content/drive/MyDrive/Colab Notebooks/2cost-revenue-clean.csv')

data.describe()

plt.figure( figsize=(10,6) )
x = DataFrame (data , columns= ['production_budget_usd'])
y = DataFrame (data , columns= ['worldwide_gross_usd'])
plt.scatter(x , y , alpha=0.3)
plt.title('Film Cost Vs Global Revenue')
plt.xlabel('Production Budget $')
plt.ylabel('Worldwide Budget $')
plt.ylim( 0 , 3000000000 )
plt.xlim( 0 , 450000000 )
plt.show()